[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Remappings tell the Solidity compiler where to find imports like `forge-std/Test.sol`.
# This maps the `forge-std/` import prefix to the vendored library in `lib/forge-std/src/`.
remappings = ["forge-std/=lib/forge-std/src/"]

[profile.ci]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["forge-std/=lib/forge-std/src/"]
verbosity = 3

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
