name: CI

permissions:
  contents: read

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      
      - name: Initialize and update submodules
        run: |
          git submodule init
          git submodule update --recursive
      
      - name: Install Forge dependencies
        run: forge install --no-commit

      - name: Verify dependencies
        run: |
          echo "Checking if forge-std exists..."
          ls -la lib/
          ls -la lib/forge-std/src/ || echo "forge-std/src not found"
          echo "Current working directory: $(pwd)"

      - name: Run Forge fmt
        run: forge fmt --check

      - name: Run Forge build
        run: forge build --sizes

      - name: Run Forge tests
        run: forge test -vvv
